name: docs
on: [push]
#  push:
#    branches:
#      - master

jobs:
  main-tests:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: gh-pages
      - uses: actions/setup-node@v1
        with:
          node-version: '10.16'
      - run: git rebase origin/master
      - run: npm run storybook:build
